-- Databricks notebook source
-- MAGIC %md
-- MAGIC # Airlines Data Product — SDP Pipeline
-- MAGIC *Generated by Genie Code* | Bronze → Silver → Gold medallion architecture built from data profiling findings.
-- MAGIC
-- MAGIC **Pipeline name:** Airlines-Data-Product
-- MAGIC
-- MAGIC This pipeline addresses all 8 data quality issues identified during profiling.

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Bronze Layer
-- MAGIC Raw ingestion as streaming tables — capture data as-is for auditability.

-- COMMAND ----------
--- hello --- 

-- DBTITLE 1,Bronze: Flights
CREATE OR REFRESH MATERIALIZED VIEW bronze_flights
COMMENT "Raw flight records — unmodified from source"
AS SELECT *, current_timestamp() AS ingested_at
FROM ${catalog}.raw_airlines.flights;

-- COMMAND ----------

-- DBTITLE 1,Bronze: Airports
CREATE OR REFRESH MATERIALIZED VIEW bronze_airports
COMMENT "Raw airport reference data — unmodified from source"
AS SELECT *, current_timestamp() AS ingested_at
FROM ${catalog}.raw_airlines.airports;

-- COMMAND ----------

-- DBTITLE 1,Bronze: Lookup Codes
CREATE OR REFRESH MATERIALIZED VIEW bronze_lookupcodes
COMMENT "Raw lookup code reference data — unmodified from source"
AS SELECT *, current_timestamp() AS ingested_at
FROM ${catalog}.raw_airlines.lookupcodes;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Silver Layer
-- MAGIC Cleaned and validated data with SDP expectations enforcing quality rules from profiling.

-- COMMAND ----------

-- DBTITLE 1,Silver: Flights (cleaned + deduplicated)
CREATE OR REFRESH MATERIALIZED VIEW silver_flights (
  -- Expectation: No null origins (Finding #1)
  CONSTRAINT valid_origin EXPECT (origin IS NOT NULL) ON VIOLATION DROP ROW,
  -- Expectation: No null destinations (Finding #1)
  CONSTRAINT valid_destination EXPECT (destination IS NOT NULL) ON VIOLATION DROP ROW,
  -- Expectation: No duplicate flight IDs (Finding #2)
  CONSTRAINT unique_flight EXPECT (row_num = 1) ON VIOLATION DROP ROW,
  -- Expectation: Distance must be positive (Finding #5)
  CONSTRAINT positive_distance EXPECT (clean_distance > 0) ON VIOLATION DROP ROW,
  -- Expectation: No future dates (Finding #6)
  CONSTRAINT valid_date EXPECT (departure_date <= current_date()) ON VIOLATION DROP ROW
)
COMMENT "Cleaned flight data — deduplicated, validated, and normalized"
AS
SELECT
  flight_id,
  UPPER(carrier) AS carrier,                          -- Fix Finding #4: normalize case
  TRIM(origin) AS origin,
  TRIM(destination) AS destination,
  departure_date,
  departure_time,
  arrival_time,
  ABS(distance) AS clean_distance,                    -- Fix Finding #5: absolute value
  delay_minutes,
  CASE
    WHEN cancellation_code IN ('A','B','C','D') THEN cancellation_code
    ELSE NULL                                          -- Fix Finding #7: invalid codes → NULL
  END AS cancellation_code,
  diverted,
  ingested_at,
  ROW_NUMBER() OVER (PARTITION BY flight_id ORDER BY ingested_at DESC) AS row_num  -- Fix Finding #2
FROM LIVE.bronze_flights;

-- COMMAND ----------

-- DBTITLE 1,Silver: Airports (cleaned)
CREATE OR REFRESH MATERIALIZED VIEW silver_airports (
  CONSTRAINT valid_airport_code EXPECT (airport_code IS NOT NULL) ON VIOLATION DROP ROW
)
COMMENT "Cleaned airport reference data — trimmed strings"
AS
SELECT
  TRIM(airport_code) AS airport_code,
  TRIM(airport_name) AS airport_name,                  -- Fix Finding #8: trim whitespace
  TRIM(city) AS city,                                   -- Fix Finding #8: trim whitespace
  TRIM(state) AS state,
  TRIM(country) AS country,
  latitude,
  longitude,
  ingested_at
FROM LIVE.bronze_airports;

-- COMMAND ----------

-- DBTITLE 1,Silver: Lookup Codes
CREATE OR REFRESH MATERIALIZED VIEW silver_lookupcodes
COMMENT "Cleaned lookup codes"
AS SELECT * FROM LIVE.bronze_lookupcodes;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Gold Layer
-- MAGIC Star schema with dimension and fact tables for analytics consumption.

-- COMMAND ----------

-- DBTITLE 1,Gold: Dimension — Airports
CREATE OR REFRESH MATERIALIZED VIEW gold_dim_airports
COMMENT "Airport dimension table for analytics"
AS
SELECT
  airport_code,
  airport_name,
  city,
  state,
  country,
  latitude,
  longitude
FROM LIVE.silver_airports;

-- COMMAND ----------

-- DBTITLE 1,Gold: Dimension — Carriers
CREATE OR REFRESH MATERIALIZED VIEW gold_dim_carriers
COMMENT "Carrier dimension table — joined with lookup codes for descriptions"
AS
SELECT
  lc.code AS carrier_code,
  lc.description AS carrier_name
FROM LIVE.silver_lookupcodes lc
WHERE lc.code_type = 'carrier';

-- COMMAND ----------

-- DBTITLE 1,Gold: Dimension — Date
CREATE OR REFRESH MATERIALIZED VIEW gold_dim_date
COMMENT "Date dimension derived from flight departure dates"
AS
SELECT DISTINCT
  departure_date AS date_key,
  YEAR(departure_date) AS year,
  QUARTER(departure_date) AS quarter,
  MONTH(departure_date) AS month,
  DAY(departure_date) AS day,
  DAYOFWEEK(departure_date) AS day_of_week,
  DATE_FORMAT(departure_date, 'EEEE') AS day_name,
  DATE_FORMAT(departure_date, 'MMMM') AS month_name,
  WEEKOFYEAR(departure_date) AS week_of_year
FROM LIVE.silver_flights;

-- COMMAND ----------

-- DBTITLE 1,Gold: Fact — Flights
CREATE OR REFRESH MATERIALIZED VIEW gold_fact_flights
COMMENT "Flight fact table — cleaned, enriched, ready for analytics"
AS
SELECT
  f.flight_id,
  f.carrier AS carrier_code,
  c.carrier_name,
  f.origin AS origin_code,
  o.airport_name AS origin_airport,
  o.city AS origin_city,
  o.state AS origin_state,
  f.destination AS dest_code,
  d.airport_name AS dest_airport,
  d.city AS dest_city,
  d.state AS dest_state,
  f.departure_date,
  f.departure_time,
  f.arrival_time,
  f.clean_distance AS distance_miles,
  f.delay_minutes,
  CASE WHEN f.delay_minutes > 0 THEN 1 ELSE 0 END AS is_delayed,
  CASE WHEN f.delay_minutes > 60 THEN 1 ELSE 0 END AS is_severely_delayed,
  f.cancellation_code,
  CASE WHEN f.cancellation_code IS NOT NULL THEN 1 ELSE 0 END AS is_cancelled,
  f.diverted
FROM LIVE.silver_flights f
LEFT JOIN LIVE.gold_dim_carriers c ON f.carrier = c.carrier_code
LEFT JOIN LIVE.silver_airports o ON f.origin = o.airport_code
LEFT JOIN LIVE.silver_airports d ON f.destination = d.airport_code;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Pipeline Summary
-- MAGIC
-- MAGIC | Layer | Tables | Purpose |
-- MAGIC |-------|--------|---------|
-- MAGIC | **Bronze** | `bronze_flights`, `bronze_airports`, `bronze_lookupcodes` | Raw ingestion with timestamp |
-- MAGIC | **Silver** | `silver_flights`, `silver_airports`, `silver_lookupcodes` | Cleaned, deduplicated, validated with expectations |
-- MAGIC | **Gold** | `gold_dim_airports`, `gold_dim_carriers`, `gold_dim_date`, `gold_fact_flights` | Star schema for analytics |
-- MAGIC
-- MAGIC **Quality expectations enforced:**
-- MAGIC - No null origins or destinations
-- MAGIC - No duplicate flight records
-- MAGIC - Positive distances only
-- MAGIC - No future dates
-- MAGIC - Normalized carrier codes (uppercase)
-- MAGIC - Validated cancellation codes
-- MAGIC - Trimmed whitespace on all strings
